export const CSS = {
  container: {
    display: 'flex',
    width: '100vw',
    height: '85vh',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: '0.5em',
  },
  card: {
    display: 'flex',
    width: 500,
    maxHeight: 500,
    overflowY: 'auto',
    borderColor: 'lightgrey',
    borderStyle: 'solid',
    borderWidth: '1px',
  },
  card_search: {
    display: 'flex',
    justifyContent: 'center',
    width: 500,
    borderColor: 'lightgrey',
    borderStyle: 'solid',
    borderWidth: '1px',
  },
  card_media: { width: '40%' },
  box: { display: 'flex', flexDirection: 'column' },
  card_content: { flex: '1 0 auto' },
  btn: { marginLeft: '1em', marginTop: '0.5em', marginBottom: '1em' },
  btn_search: { margin: 1, paddingLeft: 3, paddingRight: 3 },
  search_container: { display: 'flex', justifyContent: 'center' },
  link_audit: { display: 'flex', justifyContent: 'center' },
}
